# Sidebar navigation

- label: 'About'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Mobs and Drops
  items:
    - label: 'Item List'
      link: '/usage/item-list'
- label: Items
  items:
- label: Community
  items:
    - label: 'Changelog'
      link : '/changelog'
    - label: 'Github'
      link: https://github.com/rocketseat/gatsby-themes
